/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.30
 * Generated at: 2020-03-27 08:13:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view.inventory;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class inventory_005fsummary_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<!--   Core JS Files   -->\r\n");
      out.write("<script src=\"../assets/js/core/jquery.3.2.1.min.js\"></script>\r\n");
      out.write("<script src=\"../assets/js/core/popper.min.js\"></script>\r\n");
      out.write("<script src=\"../assets/js/core/bootstrap.min.js\"></script>\r\n");
      out.write("<!-- jQuery UI -->\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"../assets/js/plugin/jquery-ui-1.12.1.custom/jquery-ui.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"../assets/js/plugin/jquery-ui-touch-punch/jquery.ui.touch-punch.min.js\"></script>\r\n");
      out.write("<!-- Bootstrap Toggle -->\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"../assets/js/plugin/bootstrap-toggle/bootstrap-toggle.min.js\"></script>\r\n");
      out.write("<!-- jQuery Scrollbar -->\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"../assets/js/plugin/jquery-scrollbar/jquery.scrollbar.min.js\"></script>\r\n");
      out.write("<!-- Datatables -->\r\n");
      out.write("<script src=\"../assets/js/plugin/datatables/datatables.min.js\"></script>\r\n");
      out.write("<!-- Azzara JS -->\r\n");
      out.write("<script src=\"../assets/js/ready.min.js\"></script>\r\n");
      out.write("<!-- Azzara DEMO methods, don't include it in your project! -->\r\n");
      out.write("<script src=\"../assets/js/setting-demo.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(document)\r\n");
      out.write("\t\t\t.ready(\r\n");
      out.write("\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\t// Add Row\r\n");
      out.write("\t\t\t\t\t\t$('#add-row').DataTable({\r\n");
      out.write("\t\t\t\t\t\t\t\"pageLength\" : 10,\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\tvar action = '<td> <div class=\"form-button-action\"> <button type=\"button\" data-toggle=\"tooltip\" title=\"\" class=\"btn btn-link btn-primary btn-lg\" data-original-title=\"Edit Task\"> <i class=\"fa fa-edit\"></i> </button> <button type=\"button\" data-toggle=\"tooltip\" title=\"\" class=\"btn btn-link btn-danger\" data-original-title=\"Remove\"> <i class=\"fa fa-times\"></i> </button> </div> </td>';\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t$('#addRowButton').click(\r\n");
      out.write("\t\t\t\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$('#add-row').dataTable().fnAddData(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t[ $(\"#addName\").val(),\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t$(\"#addPosition\").val(),\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t$(\"#addOffice\").val(),\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\taction ]);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$('#addRowModal').modal('hide');\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("</script>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"row\">\r\n");
      out.write("\t\t<div class=\"col-md-12\">\r\n");
      out.write("\t\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t\t<div class=\"card-header\">\r\n");
      out.write("\t\t\t\t\t<div class=\"d-flex align-items-center\">\r\n");
      out.write("\t\t\t\t\t\t<h4 class=\"card-title\">Add Row</h4>\r\n");
      out.write("\t\t\t\t\t\t<button class=\"btn btn-primary btn-round ml-auto\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-toggle=\"modal\" data-target=\"#addRowModal\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"fa fa-plus\"></i> Add Row\r\n");
      out.write("\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t<!-- Modal -->\r\n");
      out.write("\t\t\t\t\t<div class=\"modal fade\" id=\"addRowModal\" tabindex=\"-1\"\r\n");
      out.write("\t\t\t\t\t\trole=\"dialog\" aria-hidden=\"true\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"modal-header no-bd\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h5 class=\"modal-title\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"fw-mediumbold\"> New</span> <span class=\"fw-light\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tRow </span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\taria-label=\"Close\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"small\">Create a new row using this form, make\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsure you fill them all</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<form>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-sm-12\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group form-group-default\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label>Name</label> <input id=\"addName\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"form-control\" placeholder=\"fill name\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-6 pr-0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group form-group-default\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label>Position</label> <input id=\"addPosition\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"form-control\" placeholder=\"fill position\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<div class=\"col-md-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group form-group-default\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label>Office</label> <input id=\"addOffice\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"form-control\" placeholder=\"fill office\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"modal-footer no-bd\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button type=\"button\" id=\"addRowButton\" class=\"btn btn-primary\">Add</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-danger\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tdata-dismiss=\"modal\">Close</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"table-responsive\">\r\n");
      out.write("\t\t\t\t\t\t<table id=\"add-row\"\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"display table table-striped table-hover\">\r\n");
      out.write("\t\t\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>Name</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>Position</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>Office</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th style=\"width: 10%\">Action</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t\t\t<tfoot>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>Name</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>Position</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>Office</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<th>Action</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</tfoot>\r\n");
      out.write("\t\t\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>Tiger Nixon</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>System Architect</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>Edinburgh</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-button-action\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button type=\"button\" data-toggle=\"tooltip\" title=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"btn btn-link btn-primary btn-lg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdata-original-title=\"Edit Task\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-edit\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button type=\"button\" data-toggle=\"tooltip\" title=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"btn btn-link btn-danger\" data-original-title=\"Remove\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-times\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>Garrett Winters</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>Accountant</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>Tokyo</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-button-action\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button type=\"button\" data-toggle=\"tooltip\" title=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"btn btn-link btn-primary btn-lg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdata-original-title=\"Edit Task\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-edit\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button type=\"button\" data-toggle=\"tooltip\" title=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"btn btn-link btn-danger\" data-original-title=\"Remove\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-times\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>Ashton Cox</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>Junior Technical Author</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>San Francisco</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-button-action\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button type=\"button\" data-toggle=\"tooltip\" title=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"btn btn-link btn-primary btn-lg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdata-original-title=\"Edit Task\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-edit\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button type=\"button\" data-toggle=\"tooltip\" title=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"btn btn-link btn-danger\" data-original-title=\"Remove\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-times\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>Cedric Kelly</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>Senior Javascript Developer</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>Edinburgh</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-button-action\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button type=\"button\" data-toggle=\"tooltip\" title=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"btn btn-link btn-primary btn-lg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdata-original-title=\"Edit Task\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-edit\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button type=\"button\" data-toggle=\"tooltip\" title=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"btn btn-link btn-danger\" data-original-title=\"Remove\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-times\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>Airi Satou</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>Accountant</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>Tokyo</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-button-action\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button type=\"button\" data-toggle=\"tooltip\" title=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"btn btn-link btn-primary btn-lg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdata-original-title=\"Edit Task\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-edit\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button type=\"button\" data-toggle=\"tooltip\" title=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"btn btn-link btn-danger\" data-original-title=\"Remove\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-times\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>Brielle Williamson</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>Integration Specialist</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>New York</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-button-action\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button type=\"button\" data-toggle=\"tooltip\" title=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"btn btn-link btn-primary btn-lg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdata-original-title=\"Edit Task\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-edit\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button type=\"button\" data-toggle=\"tooltip\" title=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"btn btn-link btn-danger\" data-original-title=\"Remove\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-times\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>Herrod Chandler</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>Sales Assistant</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>San Francisco</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-button-action\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button type=\"button\" data-toggle=\"tooltip\" title=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"btn btn-link btn-primary btn-lg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdata-original-title=\"Edit Task\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-edit\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button type=\"button\" data-toggle=\"tooltip\" title=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"btn btn-link btn-danger\" data-original-title=\"Remove\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-times\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>Rhona Davidson</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>Integration Specialist</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>Tokyo</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-button-action\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button type=\"button\" data-toggle=\"tooltip\" title=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"btn btn-link btn-primary btn-lg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdata-original-title=\"Edit Task\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-edit\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button type=\"button\" data-toggle=\"tooltip\" title=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"btn btn-link btn-danger\" data-original-title=\"Remove\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-times\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>Colleen Hurst</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>Javascript Developer</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>San Francisco</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-button-action\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button type=\"button\" data-toggle=\"tooltip\" title=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"btn btn-link btn-primary btn-lg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdata-original-title=\"Edit Task\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-edit\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button type=\"button\" data-toggle=\"tooltip\" title=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"btn btn-link btn-danger\" data-original-title=\"Remove\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-times\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>Sonya Frost</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>Software Engineer</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>Edinburgh</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"form-button-action\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button type=\"button\" data-toggle=\"tooltip\" title=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"btn btn-link btn-primary btn-lg\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdata-original-title=\"Edit Task\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-edit\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<button type=\"button\" data-toggle=\"tooltip\" title=\"\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"btn btn-link btn-danger\" data-original-title=\"Remove\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-times\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Custom template | don't include it in your project! -->\r\n");
      out.write("\t<!-- <div class=\"custom-template\">\r\n");
      out.write("\t\t<div class=\"title\">Settings</div>\r\n");
      out.write("\t\t<div class=\"custom-content\">\r\n");
      out.write("\t\t\t<div class=\"switcher\">\r\n");
      out.write("\t\t\t\t<div class=\"switch-block\">\r\n");
      out.write("\t\t\t\t\t<h4>Topbar</h4>\r\n");
      out.write("\t\t\t\t\t<div class=\"btnSwitch\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"changeMainHeaderColor\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-color=\"blue\"></button>\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"selected changeMainHeaderColor\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-color=\"purple\"></button>\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"changeMainHeaderColor\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-color=\"light-blue\"></button>\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"changeMainHeaderColor\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-color=\"green\"></button>\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"changeMainHeaderColor\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-color=\"orange\"></button>\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"changeMainHeaderColor\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-color=\"red\"></button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"switch-block\">\r\n");
      out.write("\t\t\t\t\t<h4>Background</h4>\r\n");
      out.write("\t\t\t\t\t<div class=\"btnSwitch\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"changeBackgroundColor\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-color=\"bg2\"></button>\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"changeBackgroundColor selected\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-color=\"bg1\"></button>\r\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"changeBackgroundColor\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-color=\"bg3\"></button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"custom-toggle\">\r\n");
      out.write("\t\t\t<i class=\"flaticon-settings\"></i>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div> -->\r\n");
      out.write("\t<!-- End Custom template -->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
