/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.30
 * Generated at: 2020-03-27 08:13:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!--\r\n");
      out.write("\t\t\tTip 1: You can change the background color of the main header using: data-background-color=\"blue | purple | light-blue | green | orange | red\"\r\n");
      out.write("\t\t-->\r\n");
      out.write("\r\n");
      out.write("<div class=\"main-header\" data-background-color=\"red\">\r\n");
      out.write("\t<!-- Logo Header -->\r\n");
      out.write("\t<div class=\"logo-header\">\r\n");
      out.write("\r\n");
      out.write("\t\t<a href=\"index.html\" class=\"logo\"> <img\r\n");
      out.write("\t\t\tsrc=\"assets/img/logoazzara.svg\" alt=\"navbar brand\"\r\n");
      out.write("\t\t\tclass=\"navbar-brand\">\r\n");
      out.write("\t\t</a>\r\n");
      out.write("\t\t<button class=\"navbar-toggler sidenav-toggler ml-auto\" type=\"button\"\r\n");
      out.write("\t\t\tdata-toggle=\"collapse\" data-target=\"collapse\" aria-expanded=\"false\"\r\n");
      out.write("\t\t\taria-label=\"Toggle navigation\">\r\n");
      out.write("\t\t\t<span class=\"navbar-toggler-icon\"> <i class=\"fa fa-bars\"></i>\r\n");
      out.write("\t\t\t</span>\r\n");
      out.write("\t\t</button>\r\n");
      out.write("\t\t<button class=\"topbar-toggler more\">\r\n");
      out.write("\t\t\t<i class=\"fa fa-ellipsis-v\"></i>\r\n");
      out.write("\t\t</button>\r\n");
      out.write("\t\t<div class=\"navbar-minimize\">\r\n");
      out.write("\t\t\t<button class=\"btn btn-minimize btn-rounded\">\r\n");
      out.write("\t\t\t\t<i class=\"fa fa-bars\"></i>\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- End Logo Header -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- Navbar Header -->\r\n");
      out.write("\t<nav class=\"navbar navbar-header navbar-expand-lg\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t<div class=\"collapse\" id=\"search-nav\">\r\n");
      out.write("\t\t\t\t<form class=\"navbar-left navbar-form nav-search mr-md-3\">\r\n");
      out.write("\t\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"input-group-prepend\">\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-search pr-1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<i class=\"fa fa-search search-icon\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" placeholder=\"Search ...\" class=\"form-control\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<ul class=\"navbar-nav topbar-nav ml-md-auto align-items-center\">\r\n");
      out.write("\t\t\t\t<li class=\"nav-item toggle-nav-search hidden-caret\"><a\r\n");
      out.write("\t\t\t\t\tclass=\"nav-link\" data-toggle=\"collapse\" href=\"#search-nav\"\r\n");
      out.write("\t\t\t\t\trole=\"button\" aria-expanded=\"false\" aria-controls=\"search-nav\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-search\"></i>\r\n");
      out.write("\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"nav-item dropdown hidden-caret\"><a\r\n");
      out.write("\t\t\t\t\tclass=\"nav-link dropdown-toggle\" href=\"#\" id=\"messageDropdown\"\r\n");
      out.write("\t\t\t\t\trole=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\"\r\n");
      out.write("\t\t\t\t\taria-expanded=\"false\"> <i class=\"fa fa-envelope\"></i>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t<ul class=\"dropdown-menu messages-notif-box animated fadeIn\"\r\n");
      out.write("\t\t\t\t\t\taria-labelledby=\"messageDropdown\">\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"dropdown-title d-flex justify-content-between align-items-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\tMessages <a href=\"#\" class=\"small\">Mark all as read</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"message-notif-scroll scrollbar-outer\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"notif-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"notif-img\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<img src=\"assets/img/jm_denis.jpg\" alt=\"Img Profile\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"notif-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"subject\">Jimmy Denis</span> <span class=\"block\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tHow are you ? </span> <span class=\"time\">5 minutes ago</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a> <a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"notif-img\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<img src=\"assets/img/chadengle.jpg\" alt=\"Img Profile\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"notif-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"subject\">Chad</span> <span class=\"block\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tOk, Thanks ! </span> <span class=\"time\">12 minutes ago</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a> <a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"notif-img\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<img src=\"assets/img/mlane.jpg\" alt=\"Img Profile\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"notif-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"subject\">Jhon Doe</span> <span class=\"block\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tReady for the meeting today... </span> <span class=\"time\">12\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tminutes ago</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a> <a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"notif-img\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<img src=\"assets/img/talha.jpg\" alt=\"Img Profile\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"notif-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"subject\">Talha</span> <span class=\"block\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tHi, Apa Kabar ? </span> <span class=\"time\">17 minutes ago</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li><a class=\"see-all\" href=\"javascript:void(0);\">See all\r\n");
      out.write("\t\t\t\t\t\t\t\tmessages<i class=\"fa fa-angle-right\"></i>\r\n");
      out.write("\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t<li class=\"nav-item dropdown hidden-caret\"><a\r\n");
      out.write("\t\t\t\t\tclass=\"nav-link dropdown-toggle\" href=\"#\" id=\"notifDropdown\"\r\n");
      out.write("\t\t\t\t\trole=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\"\r\n");
      out.write("\t\t\t\t\taria-expanded=\"false\"> <i class=\"fa fa-bell\"></i> <span\r\n");
      out.write("\t\t\t\t\t\tclass=\"notification\">4</span>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t<ul class=\"dropdown-menu notif-box animated fadeIn\"\r\n");
      out.write("\t\t\t\t\t\taria-labelledby=\"notifDropdown\">\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"dropdown-title\">You have 4 new notification</div>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"notif-scroll scrollbar-outer\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"notif-center\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"notif-icon notif-primary\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-user-plus\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"notif-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"block\"> New user registered </span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"time\">5 minutes ago</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a> <a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"notif-icon notif-success\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-comment\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"notif-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"block\"> Rahmad commented on Admin </span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"time\">12 minutes ago</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a> <a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"notif-img\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<img src=\"assets/img/profile2.jpg\" alt=\"Img Profile\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"notif-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"block\"> Reza send messages to you </span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"time\">12 minutes ago</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a> <a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"notif-icon notif-danger\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa fa-heart\"></i>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"notif-content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t<span class=\"block\"> Farrah liked Admin </span> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tclass=\"time\">17 minutes ago</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li><a class=\"see-all\" href=\"javascript:void(0);\">See all\r\n");
      out.write("\t\t\t\t\t\t\t\tnotifications<i class=\"fa fa-angle-right\"></i>\r\n");
      out.write("\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t<li class=\"nav-item dropdown hidden-caret\"><a\r\n");
      out.write("\t\t\t\t\tclass=\"dropdown-toggle profile-pic\" data-toggle=\"dropdown\" href=\"#\"\r\n");
      out.write("\t\t\t\t\taria-expanded=\"false\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"avatar-sm\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"assets/img/profile.jpg\" alt=\"...\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"avatar-img rounded-circle\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t<ul class=\"dropdown-menu dropdown-user animated fadeIn\">\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"user-box\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"avatar-lg\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"assets/img/profile.jpg\" alt=\"image profile\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"avatar-img rounded\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"u-text\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<h4>Hizrian</h4>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<p class=\"text-muted\">hello@example.com</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a href=\"profile.html\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tclass=\"btn btn-rounded btn-danger btn-sm\">View Profile</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"dropdown-divider\"></div> <a class=\"dropdown-item\"\r\n");
      out.write("\t\t\t\t\t\t\thref=\"#\">My Profile</a> <a class=\"dropdown-item\" href=\"#\">My\r\n");
      out.write("\t\t\t\t\t\t\t\tBalance</a> <a class=\"dropdown-item\" href=\"#\">Inbox</a>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"dropdown-divider\"></div> <a class=\"dropdown-item\"\r\n");
      out.write("\t\t\t\t\t\t\thref=\"#\">Account Setting</a>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"dropdown-divider\"></div> <a class=\"dropdown-item\"\r\n");
      out.write("\t\t\t\t\t\t\thref=\"#\">Logout</a>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t</ul></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\t<!-- End Navbar -->\r\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
