/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.30
 * Generated at: 2020-03-27 08:13:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class sidebar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!-- Sidebar START -->\r\n");
      out.write("<div class=\"sidebar\">\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"sidebar-background\"></div>\r\n");
      out.write("\t<div class=\"sidebar-wrapper scrollbar-inner\">\r\n");
      out.write("\t\t<div class=\"sidebar-content\">\r\n");
      out.write("\t\t\t<div class=\"user\">\r\n");
      out.write("\t\t\t\t<div class=\"avatar-sm float-left mr-2\">\r\n");
      out.write("\t\t\t\t\t<img src=\"assets/img/profile.jpg\" alt=\"...\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"avatar-img rounded-circle\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"info\">\r\n");
      out.write("\t\t\t\t\t<a data-toggle=\"collapse\" href=\"#collapseExample\"\r\n");
      out.write("\t\t\t\t\t\taria-expanded=\"true\"> <span> Hizrian <span\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"user-level\">Administrator</span> <span class=\"caret\"></span>\r\n");
      out.write("\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t<div class=\"clearfix\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"collapse in\" id=\"collapseExample\">\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"nav\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#profile\"> <span class=\"link-collapse\">My\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tProfile</span>\r\n");
      out.write("\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#edit\"> <span class=\"link-collapse\">Edit\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tProfile</span>\r\n");
      out.write("\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#settings\"> <span class=\"link-collapse\">Settings</span>\r\n");
      out.write("\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<ul class=\"nav\">\r\n");
      out.write("\t\t\t\t<li class=\"nav-item active\"><a href=\"index.html\"> <i\r\n");
      out.write("\t\t\t\t\t\tclass=\"fas fa-home\"></i>\r\n");
      out.write("\t\t\t\t\t\t<p>Dashboard</p> <span class=\"badge badge-count\">5</span>\r\n");
      out.write("\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"nav-section\"><span class=\"sidebar-mini-icon\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fa fa-ellipsis-h\"></i>\r\n");
      out.write("\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t<h4 class=\"text-section\">Components</h4></li>\r\n");
      out.write("\t\t\t\t<li class=\"nav-item\"><a data-toggle=\"collapse\" href=\"#base\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fas fa-layer-group\"></i>\r\n");
      out.write("\t\t\t\t\t\t<p>Base</p> <span class=\"caret\"></span>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t<div class=\"collapse\" id=\"base\">\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"nav nav-collapse\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"components/avatars.html\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"sub-item\">Avatars</span>\r\n");
      out.write("\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"components/buttons.html\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"sub-item\">Buttons</span>\r\n");
      out.write("\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"components/gridsystem.html\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"sub-item\">Grid System</span>\r\n");
      out.write("\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"components/panels.html\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"sub-item\">Panels</span>\r\n");
      out.write("\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"components/notifications.html\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"sub-item\">Notifications</span>\r\n");
      out.write("\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"components/sweetalert.html\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"sub-item\">Sweet Alert</span>\r\n");
      out.write("\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"components/font-awesome-icons.html\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"sub-item\">Font Awesome Icons</span>\r\n");
      out.write("\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"components/flaticons.html\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"sub-item\">Flaticons</span>\r\n");
      out.write("\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"components/typography.html\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"sub-item\">Typography</span>\r\n");
      out.write("\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t<li class=\"nav-item\"><a data-toggle=\"collapse\" href=\"#forms\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fas fa-pen-square\"></i>\r\n");
      out.write("\t\t\t\t\t\t<p>Forms</p> <span class=\"caret\"></span>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t<div class=\"collapse\" id=\"forms\">\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"nav nav-collapse\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"forms/forms.html\"> <span class=\"sub-item\">Basic\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tForm</span>\r\n");
      out.write("\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t<li class=\"nav-item\"><a data-toggle=\"collapse\" href=\"#tables\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fas fa-table\"></i>\r\n");
      out.write("\t\t\t\t\t\t<p>Tables</p> <span class=\"caret\"></span>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t<div class=\"collapse\" id=\"tables\">\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"nav nav-collapse\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"tables/tables.html\"> <span class=\"sub-item\">Basic\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tTable</span>\r\n");
      out.write("\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"tables/datatables.html\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"sub-item\">Datatables</span>\r\n");
      out.write("\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t<li class=\"nav-item\"><a data-toggle=\"collapse\" href=\"#maps\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fas fa-map-marker-alt\"></i>\r\n");
      out.write("\t\t\t\t\t\t<p>Maps</p> <span class=\"caret\"></span>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t<div class=\"collapse\" id=\"maps\">\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"nav nav-collapse\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"maps/googlemaps.html\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"sub-item\">Google Maps</span>\r\n");
      out.write("\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"maps/fullscreenmaps.html\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"sub-item\">Full Screen Maps</span>\r\n");
      out.write("\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"maps/jqvmap.html\"> <span class=\"sub-item\">JQVMap</span>\r\n");
      out.write("\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t<li class=\"nav-item\"><a data-toggle=\"collapse\" href=\"#charts\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"far fa-chart-bar\"></i>\r\n");
      out.write("\t\t\t\t\t\t<p>Charts</p> <span class=\"caret\"></span>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t<div class=\"collapse\" id=\"charts\">\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"nav nav-collapse\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"charts/charts.html\"> <span class=\"sub-item\">Chart\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tJs</span>\r\n");
      out.write("\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"charts/sparkline.html\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"sub-item\">Sparkline</span>\r\n");
      out.write("\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"nav-item\"><a href=\"widgets.html\"> <i\r\n");
      out.write("\t\t\t\t\t\tclass=\"fas fa-desktop\"></i>\r\n");
      out.write("\t\t\t\t\t\t<p>Widgets</p> <span class=\"badge badge-count badge-success\">4</span>\r\n");
      out.write("\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t<li class=\"nav-item\"><a data-toggle=\"collapse\"\r\n");
      out.write("\t\t\t\t\thref=\"#custompages\"> <i class=\"fas fa-paint-roller\"></i>\r\n");
      out.write("\t\t\t\t\t\t<p>Custom Pages</p> <span class=\"caret\"></span>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t<div class=\"collapse\" id=\"custompages\">\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"nav nav-collapse\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"login.html\"> <span class=\"sub-item\">Login\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t& Register 1</span>\r\n");
      out.write("\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"login2.html\"> <span class=\"sub-item\">Login\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t& Register 2</span>\r\n");
      out.write("\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"userprofile.html\"> <span class=\"sub-item\">User\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tProfile</span>\r\n");
      out.write("\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"404.html\"> <span class=\"sub-item\">404</span>\r\n");
      out.write("\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t<li class=\"nav-item\"><a data-toggle=\"collapse\" href=\"#submenu\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fas fa-bars\"></i>\r\n");
      out.write("\t\t\t\t\t\t<p>Menu Levels</p> <span class=\"caret\"></span>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t<div class=\"collapse\" id=\"submenu\">\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"nav nav-collapse\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a data-toggle=\"collapse\" href=\"#subnav1\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"sub-item\">Level 1</span> <span class=\"caret\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"collapse\" id=\"subnav1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"nav nav-collapse subnav\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\"> <span class=\"sub-item\">Level\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t2</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\"> <span class=\"sub-item\">Level\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t2</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a data-toggle=\"collapse\" href=\"#subnav2\"> <span\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"sub-item\">Level 1</span> <span class=\"caret\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"collapse\" id=\"subnav2\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<ul class=\"nav nav-collapse subnav\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<li><a href=\"#\"> <span class=\"sub-item\">Level\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t2</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#\"> <span class=\"sub-item\">Level 1</span>\r\n");
      out.write("\t\t\t\t\t\t\t</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- Sidebar END -->");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
